site_name: OBIA
site_url: https://obia.sefa.ai
repo_url: https://github.com/iosefa/obia

theme:
    name: material
    palette:
        primary: green
        accent: deep-orange
    icon:
        repo: fontawesome/brands/github
    features:
        - navigation.instant
        - navigation.sections
        - search.highlight
        - search.suggest

plugins:
    - search
    - mkdocstrings:
        handlers:
            python:
                options:
                    docstring_style: google
                    show_source: true
                    show_root_heading: true
                    show_symbol_type_heading: true
    - git-revision-date-localized
    - mkdocs-jupyter:
        include_source: true
        execute: false
        ignore_h1_titles: true

markdown_extensions:
    - md_in_html
    - attr_list
    - pymdownx.superfences
    - pymdownx.arithmatex:
          generic: true
    - pymdownx.highlight:
          linenums: true
    - toc:
          permalink: true

nav:
    - Home: index.md
    - Installation: installation.md
    - Concepts: concepts.md
    - Usage:
        - Segmentation: usage/segmentation.md
        - Classification: usage/classification.md
        - Point Clouds: usage/pointcloud.md
        - Large Rasters: usage/large-rasters.md
        - Experimental Detection: usage/detection.md
    - Development:
        - Contributing: contributing.md
        - Code of Conduct: code_of_conduct.md
    - Changelog: https://github.com/iosefa/obia/releases
    - Report Issues: https://github.com/iosefa/obia/issues
    - API Reference:
        - Overview: api/index.md
        - Handlers: api/handlers.md
        - Segmentation: api/segmentation.md
        - Point Clouds: api/pointcloud.md
        - Experimental Detection: api/detection.md
        - Classification: api/classification.md
        - Utils: api/utils.md

extra_javascript:
 - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-mml-chtml.js
